<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE imobiliaria [
  <!ELEMENT imobiliaria (imovel+)>
  <!ELEMENT imovel (descricao, proprietario, endereco, caracteristicas, valor)>
  <!ELEMENT descricao (#PCDATA)>
  <!ELEMENT proprietario (nome, (email | telefone)*)>
  <!ELEMENT nome (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT telefone (#PCDATA)>
  <!ELEMENT endereco (rua, bairro, cidade, numero?)>
  <!ELEMENT rua (#PCDATA)>
  <!ELEMENT bairro (#PCDATA)>
  <!ELEMENT cidade (#PCDATA)>
  <!ELEMENT numero (#PCDATA)>
  <!ELEMENT caracteristicas (tamanho, numQuartos, numBanheiros)>
  <!ELEMENT tamanho (#PCDATA)>
  <!ELEMENT numQuartos (#PCDATA)>
  <!ELEMENT numBanheiros (#PCDATA)>
  <!ELEMENT valor (#PCDATA)>
]>

<imobiliaria>
  <imovel>
    <descricao>Casa com alpendre</descricao>
    <proprietario>
      <nome>Izaias Papinho</nome>
      <email>pipipipopopo@pipo.com</email>
      <telefone>(84) 1234-5678</telefone>
      <telefone>(84) 8765-4321</telefone>
    </proprietario>
    <endereco>
      <rua>Rua de pedrinhas de brilhantes</rua>
      <bairro>para o meu amor passar</bairro>
      <cidade>spp</cidade>
      <numero>000</numero>
    </endereco>
    <caracteristicas>
      <tamanho>300 m²</tamanho>
      <numQuartos>5</numQuartos>
      <numBanheiros>3</numBanheiros>
    </caracteristicas>
    <valor>R$ 1000.000,00</valor>
  </imovel>
  
  <imovel>
    <descricao>Apartamento capsula de café</descricao>
    <proprietario>
      <nome>Pipipi Popopo</nome>
      <email>pipipipopopo@pipo.com</email>
      <telefone>(84) 1234-5678</telefone>
    </proprietario>
    <endereco>
      <rua>Pipipi do Popopo</rua>
      <bairro>Centro</bairro>
      <cidade>spp</cidade>
    </endereco>
    <caracteristicas>
      <tamanho>10 m²</tamanho>
      <numQuartos>2</numQuartos>
      <numBanheiros>1</numBanheiros>
    </caracteristicas>
    <valor>R$ 350.000,00</valor>
  </imovel>
  
  <imovel>
    <descricao>Pipipi Popopo</descricao>
    <proprietario>
      <nome>Pipipi Popopo da Silva Sauro</nome>
      <telefone>(84) 1234-5678</telefone>
    </proprietario>
    <endereco>
      <rua>Pipipi Popopo</rua>
      <bairro>Pipipi Popopo</bairro>
      <cidade>Pipipi Popopo</cidade>
      <numero>000</numero>
    </endereco>
    <caracteristicas>
      <tamanho>50 m²</tamanho>
      <numQuartos>1</numQuartos>
      <numBanheiros>1</numBanheiros>
    </caracteristicas>
    <valor>R$ 800.000,00</valor>
  </imovel>
  
  <imovel>
    <descricao>Pipipi Popopo</descricao>
    <proprietario>
      <nome>Pipipi Popopo Gomes Gonçalves</nome>
      <email>pipipipopopo@pipo.com</email>
      <telefone>(84) 1234-5678</telefone>
    </proprietario>
    <endereco>
      <rua>Rua pipipipopopo</rua>
      <bairro>Jardim dos pipipipopopo</bairro>
      <cidade>terra do nunca</cidade>
      <numero>000</numero>
    </endereco>
    <caracteristicas>
      <tamanho>20 m²</tamanho>
      <numQuartos>2</numQuartos>
      <numBanheiros>2</numBanheiros>
    </caracteristicas>
    <valor>R$ 700.000,00</valor>
  </imovel>
  
  <imovel>
    <descricao>pipipipopopo com piscina</descricao>
    <proprietario>
      <nome>Pipipi Popopo Gomes</nome>
      <email>pipipipopopo@pipo.com</email>
      <telefone>(84) 1234-5678</telefone>
      <telefone>(84) 8765-4321</telefone>
    </proprietario>
    <endereco>
      <rua>Avenida pipipipopopo</rua>
      <bairro>Pipipipopopo</bairro>
      <cidade>spp</cidade>
      <numero>000</numero>
    </endereco>
    <caracteristicas>
      <tamanho>100 m²</tamanho>
      <numQuartos>3</numQuartos>
      <numBanheiros>2</numBanheiros>
    </caracteristicas>
    <valor>R$ 1.200.000,00</valor>
  </imovel>
</imobiliaria>